service: shuriken-note-api

image: nyshk97/shuriken-note-api

servers:
  web:
    hosts:
      - 198.13.52.210
    options:
      memory: 512m

proxy:
  ssl: true
  host: api.d0ne1s.com
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3

registry:
  server: ghcr.io
  username: nyshk97
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_LOG_TO_STDOUT: true
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 1
    S3_BUCKET_NAME: shuriken-note-storage-production
    AWS_REGION: ap-northeast-1
    CLOUDFRONT_HOST: d1dnvitqqygobe.cloudfront.net
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

accessories:
  db:
    image: ghcr.io/nyshk97/shuriken-note-postgres:17-bigm
    host: 198.13.52.210
    port: "127.0.0.1:5432:5432"
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: shuriken_note
        POSTGRES_DB: shuriken_note_production
    directories:
      - data:/var/lib/postgresql/data
    options:
      memory: 256m

volumes:
  - "shuriken_note_api_storage:/rails/storage"

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
