# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Prefer single quotes when no interpolation
Style/StringLiterals:
  EnforcedStyle: single_quotes
